export const MARKETPLACES = {
    NATIONAL: [
        { name: 'Mercado Livre', url: 'https://www.mercadolivre.com.br' },
        { name: 'OLX', url: 'https://www.olx.com.br' },
        { name: 'Shopee', url: 'https://shopee.com.br' },
        { name: 'Magazine Luiza', url: 'https://www.magazineluiza.com.br' },
        { name: 'Amazon Brasil', url: 'https://www.amazon.com.br' },
        { name: 'Casas Bahia', url: 'https://www.casasbahia.com.br' },
        { name: 'Americanas', url: 'https://www.americanas.com.br' },
        { name: 'Carrefour', url: 'https://www.carrefour.com.br' },
    ],
    VEHICLES: [
        { name: 'Webmotors', url: 'https://www.webmotors.com.br' },
        { name: 'iCarros', url: 'https://www.icarros.com.br' },
        { name: 'Mobiauto', url: 'https://www.mobiauto.com.br' },
        { name: 'UsadosBR', url: 'https://www.usadosbr.com' },
    ],
    REAL_ESTATE: [
        { name: 'ZAP Imóveis', url: 'https://www.zapimoveis.com.br' },
        { name: 'Viva Real', url: 'https://www.vivareal.com.br' },
        { name: 'QuintoAndar', url: 'https://www.quintoandar.com.br' },
    ],
    REGIONAL: {
        MG: [
            { name: 'Classificados Estado de Minas', url: 'https://classificados.em.com.br' },
            { name: 'Vrum MG', url: 'https://vrum.com.br' },
        ],
        BA: [
            { name: 'Feira do Rolo Conquista', url: 'https://feiradorolodeconquista.com.br' },
        ],
    },
};
export const CATEGORIES = [
    'eletronicos',
    'moveis',
    'veiculos',
    'imoveis',
    'moda',
    'esportes',
    'livros',
    'brinquedos',
    'ferramentas',
    'agro',
    'outros',
];
export const BRAZILIAN_STATES = [
    { code: 'AC', name: 'Acre', region: 'Norte' },
    { code: 'AL', name: 'Alagoas', region: 'Nordeste' },
    { code: 'AP', name: 'Amapá', region: 'Norte' },
    { code: 'AM', name: 'Amazonas', region: 'Norte' },
    { code: 'BA', name: 'Bahia', region: 'Nordeste' },
    { code: 'CE', name: 'Ceará', region: 'Nordeste' },
    { code: 'DF', name: 'Distrito Federal', region: 'Centro-Oeste' },
    { code: 'ES', name: 'Espírito Santo', region: 'Sudeste' },
    { code: 'GO', name: 'Goiás', region: 'Centro-Oeste' },
    { code: 'MA', name: 'Maranhão', region: 'Nordeste' },
    { code: 'MT', name: 'Mato Grosso', region: 'Centro-Oeste' },
    { code: 'MS', name: 'Mato Grosso do Sul', region: 'Centro-Oeste' },
    { code: 'MG', name: 'Minas Gerais', region: 'Sudeste' },
    { code: 'PA', name: 'Pará', region: 'Norte' },
    { code: 'PB', name: 'Paraíba', region: 'Nordeste' },
    { code: 'PR', name: 'Paraná', region: 'Sul' },
    { code: 'PE', name: 'Pernambuco', region: 'Nordeste' },
    { code: 'PI', name: 'Piauí', region: 'Nordeste' },
    { code: 'RJ', name: 'Rio de Janeiro', region: 'Sudeste' },
    { code: 'RN', name: 'Rio Grande do Norte', region: 'Nordeste' },
    { code: 'RS', name: 'Rio Grande do Sul', region: 'Sul' },
    { code: 'RO', name: 'Rondônia', region: 'Norte' },
    { code: 'RR', name: 'Roraima', region: 'Norte' },
    { code: 'SC', name: 'Santa Catarina', region: 'Sul' },
    { code: 'SP', name: 'São Paulo', region: 'Sudeste' },
    { code: 'SE', name: 'Sergipe', region: 'Nordeste' },
    { code: 'TO', name: 'Tocantins', region: 'Norte' },
];
